-- Sinh tự động bởi scripts/content-to-sql.ts — đừng sửa tay.
begin;
insert into public.sources (id,kind,title,authors,journal,publisher,year,doi,url,license,cited_by,note) values
('ta2','terminology','Terminologia Anatomica, 2nd ed. (TA2)',null,null,'FIPAT – Federative International Programme for Anatomical Terminology',2019,null,'https://fipat.library.dal.ca/ta2/','cite',null,'Chuẩn thuật ngữ Latin quốc tế; bản CSV kèm trong repo Z-Anatomy'),
('gray1918','textbook','Anatomy of the Human Body, 20th ed. – VI. The Arteries & The Heart',array['Henry Gray','Warren H. Lewis (ed.)']::text[],null,null,1918,null,'https://www.bartleby.com/107/138.html','open',null,'Public domain; hình minh họa dùng được'),
('wiki_heart','encyclopedia','Wikipedia – Heart và các bài về từng cấu trúc',null,null,null,null,null,'https://en.wikipedia.org/wiki/Heart','open',null,'CC BY-SA 4.0, tương thích license model; ghi công khi chuyển thể'),
('openstax_ap_19','textbook','Anatomy and Physiology 2e – 19.1 Heart Anatomy',array['J. Gordon Betts','Kelly A. Young','James A. Wise']::text[],null,'OpenStax',2022,null,'https://openstax.org/books/anatomy-and-physiology-2e/pages/19-1-heart-anatomy','cite',null,'CC BY-NC-SA 4.0 – điều khoản NC nên chỉ trích dẫn, không chuyển thể văn bản vào sản phẩm thu phí'),
('zanatomy','model','Z-Anatomy – The open source atlas of anatomy',null,null,null,null,null,'https://github.com/Z-Anatomy/Models-of-human-anatomy','open',null,'CC BY-SA 4.0; nguồn mô hình 3D (từ BodyParts3D, CC BY-SA 2.1 JP)'),
('haissaguerre1998','article','Spontaneous Initiation of Atrial Fibrillation by Ectopic Beats Originating in the Pulmonary Veins',array['Haïssaguerre M','et al.']::text[],'New England Journal of Medicine',null,1998,'10.1056/NEJM199809033391003','https://doi.org/10.1056/NEJM199809033391003','cite',6193,null),
('ho2002mitral','article','Anatomy of the mitral valve',array['Ho SY']::text[],'Heart',null,2002,'10.1136/heart.88.suppl_4.iv5','https://doi.org/10.1136/heart.88.suppl_4.iv5','cite',98,null),
('wilson2007svc','article','Superior Vena Cava Syndrome with Malignant Causes',array['Wilson LD','Detterbeck FC','Yahalom J']::text[],'New England Journal of Medicine',null,2007,'10.1056/NEJMcp067190','https://doi.org/10.1056/NEJMcp067190','cite',433,null),
('carapetis2016rhd','article','Acute rheumatic fever and rheumatic heart disease',array['Carapetis JR','et al.']::text[],'Nature Reviews Disease Primers',null,2016,'10.1038/nrdp.2015.84','https://doi.org/10.1038/nrdp.2015.84','cite',535,null),
('levy1990lvh','article','Prognostic Implications of Echocardiographically Determined Left Ventricular Mass in the Framingham Heart Study',array['Levy D','et al.']::text[],'New England Journal of Medicine',null,1990,'10.1056/NEJM199005313222203','https://doi.org/10.1056/NEJM199005313222203','cite',4383,null),
('piazza2008aortic','article','Anatomy of the Aortic Valvar Complex and Its Implications for Transcatheter Implantation of the Aortic Valve',array['Piazza N','et al.']::text[],'Circulation: Cardiovascular Interventions',null,2008,'10.1161/CIRCINTERVENTIONS.108.780858','https://doi.org/10.1161/CIRCINTERVENTIONS.108.780858','cite',547,null),
('angelini2007coronary','article','Coronary Artery Anomalies',array['Angelini P']::text[],'Circulation',null,2007,'10.1161/CIRCULATIONAHA.106.618082','https://doi.org/10.1161/CIRCULATIONAHA.106.618082','cite',691,null)
on conflict (id) do update set kind=excluded.kind,title=excluded.title,authors=excluded.authors,journal=excluded.journal,publisher=excluded.publisher,year=excluded.year,doi=excluded.doi,url=excluded.url,license=excluded.license,cited_by=excluded.cited_by,note=excluded.note;
insert into public.structures (id,system,mesh_names,name_vi,name_latin,name_latin_ta2,name_en,grp,layer,description,"function",clinical,mnemonic,source,reviewed_by,reviewed_at,updated_at) values
('right_atrium','cardiovascular',array['Right atrium']::text[],'Tâm nhĩ phải','Atrium dextrum',null,'Right atrium','chambers',1,'Buồng tim ở phía trên bên phải, nhận máu từ tĩnh mạch chủ trên, tĩnh mạch chủ dưới và xoang vành. Mặt trong có phần thành nhẵn và phần có cơ lược.','Thu nhận máu nghèo oxy từ toàn cơ thể và đẩy xuống tâm thất phải qua van ba lá.','Nút xoang nhĩ (nút tạo nhịp tự nhiên) nằm ở thành tâm nhĩ phải, gần lỗ tĩnh mạch chủ trên.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('right_ventricle','cardiovascular',array['Right ventricle']::text[],'Tâm thất phải','Ventriculus dexter',null,'Right ventricle','chambers',1,'Buồng tim ở phía trước, tạo nên phần lớn mặt ức sườn của tim. Thành mỏng hơn tâm thất trái, mặt trong có nhiều bè cơ.','Bơm máu nghèo oxy lên phổi qua van động mạch phổi và thân động mạch phổi.','Phì đại thất phải gặp trong tăng áp động mạch phổi kéo dài.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('left_atrium','cardiovascular',array['Left atrium']::text[],'Tâm nhĩ trái','Atrium sinistrum',null,'Left atrium','chambers',1,'Buồng tim ở phía sau, nhận máu từ bốn tĩnh mạch phổi. Tạo nên phần lớn nền tim.','Thu nhận máu giàu oxy từ phổi và đẩy xuống tâm thất trái qua van hai lá.','Giãn nhĩ trái thường gặp trong hẹp van hai lá và là yếu tố nguy cơ của rung nhĩ.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('left_ventricle','cardiovascular',array['Left ventricle']::text[],'Tâm thất trái','Ventriculus sinister',null,'Left ventricle','chambers',1,'Buồng tim có thành dày nhất, tạo nên mỏm tim và phần lớn mặt hoành của tim.','Bơm máu giàu oxy vào động mạch chủ để đi nuôi toàn cơ thể.','Phì đại thất trái là hậu quả thường gặp của tăng huyết áp kéo dài.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('papillary_muscles_rv','cardiovascular',array['Anterior papillary muscle of right ventricle','Inferior papillary muscle of right ventricle','Septal papillary muscle of right ventricle']::text[],'Cơ nhú tâm thất phải','Musculi papillares ventriculi dextri',null,'Papillary muscles of right ventricle','chambers',2,'Ba cơ nhú (trước, dưới và vách) nằm trong tâm thất phải, nối với các lá van ba lá bằng thừng gân.','Co cùng tâm thất để giữ các lá van ba lá không lật ngược lên tâm nhĩ trong thì tâm thu.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('papillary_muscle_lv','cardiovascular',array['Inferior papillary muscle of left ventricle']::text[],'Cơ nhú tâm thất trái','Musculi papillares ventriculi sinistri',null,'Papillary muscles of left ventricle','chambers',2,'Hai cơ nhú (trước và sau) nằm trong tâm thất trái, nối với hai lá van hai lá bằng thừng gân. Mô hình chỉ có cơ nhú sau; cơ nhú trước không có trong dữ liệu nguồn.','Giữ các lá van hai lá đóng kín trong thì tâm thu.','Đứt cơ nhú sau nhồi máu cơ tim gây hở van hai lá cấp.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('tricuspid_valve','cardiovascular',array['Inferior leaflet of right atrioventricular valve','Septal leaflet of right atrioventricular valve']::text[],'Van ba lá','Valva tricuspidalis (valva atrioventricularis dextra)','Valva atrioventricularis dextra','Tricuspid valve','valves',2,'Van nhĩ thất phải, có ba lá van (trước, sau và vách), nằm giữa tâm nhĩ phải và tâm thất phải. Mô hình có lá sau và lá vách; lá trước không có trong dữ liệu nguồn.','Ngăn máu trào ngược từ tâm thất phải lên tâm nhĩ phải trong thì tâm thu.','Nghe rõ nhất ở bờ trái xương ức, khoang liên sườn 4–5.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('mitral_valve','cardiovascular',array['Posterior leaflet of left atrioventricular valve']::text[],'Van hai lá','Valva mitralis (valva atrioventricularis sinistra)','Valva atrioventricularis sinistra','Mitral valve','valves',2,'Van nhĩ thất trái, có hai lá van (lá trước và lá sau), nằm giữa tâm nhĩ trái và tâm thất trái. Mô hình hiển thị van như một khối, không tách riêng hai lá.','Ngăn máu trào ngược từ tâm thất trái lên tâm nhĩ trái trong thì tâm thu.','Hẹp van hai lá thường do thấp tim; nghe rõ nhất ở mỏm tim.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('aortic_valve','cardiovascular',array['Left coronary leaflet','Right coronary leaflet','Non-coronary leaflet']::text[],'Van động mạch chủ','Valva aortae',null,'Aortic valve','valves',2,'Van bán nguyệt có ba lá: lá vành trái, lá vành phải và lá không vành. Phía trên các lá van là các xoang động mạch chủ.','Ngăn máu từ động mạch chủ chảy ngược về tâm thất trái trong thì tâm trương.','Động mạch vành trái và phải xuất phát từ xoang vành trái và phải ngay trên van.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('pulmonary_valve','cardiovascular',array['Anterior semilunar leaflet of pulmonary valve','Left semilunar leaflet of pulmonary valve','Right semilunar leaflet of pulmonary valve']::text[],'Van động mạch phổi','Valva trunci pulmonalis',null,'Pulmonary valve','valves',2,'Van bán nguyệt có ba lá (trước, trái, phải), nằm ở lỗ thân động mạch phổi.','Ngăn máu từ thân động mạch phổi chảy ngược về tâm thất phải trong thì tâm trương.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('ascending_aorta','cardiovascular',array['Ascending aorta']::text[],'Động mạch chủ lên','Pars ascendens aortae','Aorta ascendens','Ascending aorta','great_arteries',0,'Đoạn đầu của động mạch chủ, dài khoảng 5 cm, đi từ tâm thất trái lên đến chỗ bắt đầu cung động mạch chủ.','Dẫn máu từ tâm thất trái; cho hai nhánh đầu tiên là động mạch vành trái và phải.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('aortic_arch','cardiovascular',array['Aortic arch']::text[],'Cung động mạch chủ','Arcus aortae',null,'Aortic arch','great_arteries',0,'Đoạn cong của động mạch chủ, uốn từ trước ra sau và sang trái, phía trên chỗ chia đôi của thân động mạch phổi.','Cho ba nhánh lớn cấp máu cho đầu, cổ và chi trên: thân cánh tay đầu, động mạch cảnh chung trái, động mạch dưới đòn trái.','Dây chằng động mạch (di tích ống động mạch) nối cung động mạch chủ với động mạch phổi trái.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('thoracic_aorta','cardiovascular',array['Thoracic aorta']::text[],'Động mạch chủ ngực','Pars thoracica aortae','Aorta thoracica','Thoracic (descending) aorta','great_arteries',0,'Đoạn động mạch chủ xuống nằm trong trung thất sau, từ bờ dưới đốt sống ngực IV đến lỗ động mạch chủ của cơ hoành.','Cấp máu cho thành ngực và các tạng trong ngực qua các động mạch gian sườn sau, phế quản, thực quản.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('brachiocephalic_trunk','cardiovascular',array['Brachiocephalic trunk']::text[],'Thân cánh tay đầu','Truncus brachiocephalicus',null,'Brachiocephalic trunk','great_arteries',0,'Nhánh đầu tiên và lớn nhất của cung động mạch chủ, chia thành động mạch cảnh chung phải và động mạch dưới đòn phải.','Cấp máu cho nửa phải của đầu, cổ và chi trên phải.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('right_common_carotid','cardiovascular',array['Right common carotid artery']::text[],'Động mạch cảnh chung phải','Arteria carotis communis dextra','Carotis communis dextra','Right common carotid artery','great_arteries',0,'Xuất phát từ thân cánh tay đầu, đi lên cổ trong bao cảnh và chia thành động mạch cảnh trong và cảnh ngoài.','Cấp máu cho đầu và cổ bên phải.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('left_common_carotid','cardiovascular',array['Left common carotid artery']::text[],'Động mạch cảnh chung trái','Arteria carotis communis sinistra','Carotis communis sinistra','Left common carotid artery','great_arteries',0,'Xuất phát trực tiếp từ cung động mạch chủ, dài hơn bên phải vì có thêm đoạn trong ngực.','Cấp máu cho đầu và cổ bên trái.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('right_subclavian','cardiovascular',array['Right subclavian artery']::text[],'Động mạch dưới đòn phải','Arteria subclavia dextra',null,'Right subclavian artery','great_arteries',0,'Xuất phát từ thân cánh tay đầu, uốn cong qua đỉnh phổi và đi ra ngoài phía sau xương đòn.','Cấp máu cho chi trên phải, một phần cổ và não (qua động mạch đốt sống).',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('left_subclavian','cardiovascular',array['Left subclavian artery']::text[],'Động mạch dưới đòn trái','Arteria subclavia sinistra',null,'Left subclavian artery','great_arteries',0,'Nhánh thứ ba của cung động mạch chủ, đi lên rồi ra ngoài qua đỉnh phổi trái.','Cấp máu cho chi trên trái, một phần cổ và não.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('pulmonary_trunk','cardiovascular',array['Pulmonary trunk','Bifurcation of pulmonary trunk']::text[],'Thân động mạch phổi','Truncus pulmonalis',null,'Pulmonary trunk','great_arteries',0,'Xuất phát từ tâm thất phải, dài khoảng 5 cm, đi lên và ra sau rồi chia thành động mạch phổi phải và trái dưới cung động mạch chủ.','Dẫn máu nghèo oxy từ tâm thất phải lên phổi.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('right_pulmonary_artery','cardiovascular',array['Right pulmonary artery']::text[],'Động mạch phổi phải','Arteria pulmonalis dextra',null,'Right pulmonary artery','great_arteries',0,'Nhánh dài hơn của thân động mạch phổi, đi ngang sang phải phía sau động mạch chủ lên và tĩnh mạch chủ trên để vào rốn phổi phải.','Dẫn máu nghèo oxy đến phổi phải.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('left_pulmonary_artery','cardiovascular',array['Left pulmonary artery']::text[],'Động mạch phổi trái','Arteria pulmonalis sinistra',null,'Left pulmonary artery','great_arteries',0,'Nhánh ngắn hơn, đi sang trái phía trước động mạch chủ xuống để vào rốn phổi trái.','Dẫn máu nghèo oxy đến phổi trái.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('superior_vena_cava','cardiovascular',array['Superior vena cava']::text[],'Tĩnh mạch chủ trên','Vena cava superior',null,'Superior vena cava','great_veins',0,'Được tạo bởi hai tĩnh mạch cánh tay đầu hợp lại, đi xuống bên phải động mạch chủ lên và đổ vào phần trên tâm nhĩ phải.','Dẫn máu nghèo oxy từ đầu, cổ, chi trên và thành ngực về tim.','Hội chứng tĩnh mạch chủ trên: phù mặt, cổ và chi trên do khối u trung thất chèn ép.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('inferior_vena_cava','cardiovascular',array['Inferior vena cava (thoracic part)']::text[],'Tĩnh mạch chủ dưới','Vena cava inferior',null,'Inferior vena cava','great_veins',0,'Tĩnh mạch lớn nhất cơ thể, đi qua lỗ tĩnh mạch chủ của cơ hoành ở mức đốt sống ngực VIII và đổ vào phần dưới tâm nhĩ phải. Mô hình chỉ có đoạn ngực.','Dẫn máu nghèo oxy từ phần cơ thể dưới cơ hoành về tim.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('right_brachiocephalic_vein','cardiovascular',array['Right brachiocephalic vein']::text[],'Tĩnh mạch cánh tay đầu phải','Vena brachiocephalica dextra',null,'Right brachiocephalic vein','great_veins',0,'Do tĩnh mạch cảnh trong phải và tĩnh mạch dưới đòn phải hợp thành sau khớp ức đòn phải, ngắn và đi gần thẳng đứng.','Cùng tĩnh mạch cánh tay đầu trái tạo nên tĩnh mạch chủ trên.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('left_brachiocephalic_vein','cardiovascular',array['Left brachiocephalic vein']::text[],'Tĩnh mạch cánh tay đầu trái','Vena brachiocephalica sinistra',null,'Left brachiocephalic vein','great_veins',0,'Dài hơn bên phải, đi chếch sang phải phía sau cán ức, bắt chéo trước các nhánh của cung động mạch chủ.','Cùng tĩnh mạch cánh tay đầu phải tạo nên tĩnh mạch chủ trên.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('right_pulmonary_veins','cardiovascular',array['Right superior pulmonary vein','Right inferior pulmonary vein']::text[],'Các tĩnh mạch phổi phải','Venae pulmonales dextrae','Vena pulmonalis dextra superior; Vena pulmonalis dextra inferior','Right pulmonary veins','great_veins',0,'Hai tĩnh mạch (trên và dưới) đi từ rốn phổi phải, phía sau tĩnh mạch chủ trên và tâm nhĩ phải, đổ vào tâm nhĩ trái.','Dẫn máu giàu oxy từ phổi phải về tâm nhĩ trái.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('left_pulmonary_veins','cardiovascular',array['Left superior pulmonary vein','Left inferior pulmonary vein']::text[],'Các tĩnh mạch phổi trái','Venae pulmonales sinistrae','Vena pulmonalis sinistra superior; Vena pulmonalis sinistra inferior','Left pulmonary veins','great_veins',0,'Hai tĩnh mạch (trên và dưới) đi từ rốn phổi trái, phía trước động mạch chủ xuống, đổ vào tâm nhĩ trái.','Dẫn máu giàu oxy từ phổi trái về tâm nhĩ trái.','Tĩnh mạch phổi là nguồn phát sinh thường gặp của rung nhĩ; là đích của thủ thuật cô lập tĩnh mạch phổi.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('left_coronary_artery','cardiovascular',array['Left coronary artery']::text[],'Động mạch vành trái','Arteria coronaria sinistra',null,'Left coronary artery','coronary',0,'Xuất phát từ xoang động mạch chủ trái, thân chung ngắn (khoảng 1–2 cm) rồi chia thành nhánh gian thất trước và nhánh mũ.','Cấp máu cho phần lớn tâm thất trái, tâm nhĩ trái và vách gian thất.','Hẹp thân chung động mạch vành trái là tổn thương nguy hiểm, thường chỉ định phẫu thuật bắc cầu.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('anterior_interventricular_artery','cardiovascular',array['Anterior interventricular artery','Septal branches of anterior interventricular artery']::text[],'Nhánh gian thất trước','Ramus interventricularis anterior','Arteria interventricularis anterior','Anterior interventricular (LAD) artery','coronary',0,'Nhánh của động mạch vành trái, chạy trong rãnh gian thất trước xuống mỏm tim, cho các nhánh vách và nhánh chéo.','Cấp máu cho thành trước hai tâm thất và hai phần ba trước của vách gian thất.','Tắc nhánh gian thất trước là nguyên nhân thường gặp nhất của nhồi máu cơ tim thành trước.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('circumflex_artery','cardiovascular',array['Circumflex artery of heart']::text[],'Nhánh mũ','Ramus circumflexus','Arteria circumflexa cordis','Circumflex artery','coronary',0,'Nhánh của động mạch vành trái, chạy trong rãnh vành vòng ra sau bên trái tim.','Cấp máu cho tâm nhĩ trái và thành bên, thành sau tâm thất trái.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('right_coronary_artery','cardiovascular',array['Right coronary artery','Right inferolateral branch of right coronary artery']::text[],'Động mạch vành phải','Arteria coronaria dextra',null,'Right coronary artery','coronary',0,'Xuất phát từ xoang động mạch chủ phải, chạy trong rãnh vành phải ra sau, thường tận cùng bằng nhánh gian thất sau.','Cấp máu cho tâm nhĩ phải, tâm thất phải, thường cả nút xoang nhĩ, nút nhĩ thất và phần sau vách gian thất.','Nhồi máu do tắc động mạch vành phải thường kèm rối loạn nhịp chậm do thiếu máu nút nhĩ thất.',null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('coronary_sinus','cardiovascular',array['Coronary sinus']::text[],'Xoang vành','Sinus coronarius',null,'Coronary sinus','coronary',0,'Tĩnh mạch lớn nằm trong rãnh vành ở mặt sau tim, dài khoảng 2–3 cm, đổ vào tâm nhĩ phải giữa lỗ tĩnh mạch chủ dưới và van ba lá.','Thu nhận phần lớn máu tĩnh mạch của tim (tĩnh mạch tim lớn, giữa, nhỏ) đưa về tâm nhĩ phải.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('great_cardiac_vein','cardiovascular',array['Great cardiac vein']::text[],'Tĩnh mạch tim lớn','Vena cordis magna','Vena magna cordis','Great cardiac vein','coronary',0,'Bắt đầu ở mỏm tim, đi lên trong rãnh gian thất trước cùng nhánh gian thất trước, vòng sang trái trong rãnh vành rồi đổ vào xoang vành.','Dẫn máu tĩnh mạch từ thành trước tim về xoang vành.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('middle_cardiac_vein','cardiovascular',array['Middle cardiac vein']::text[],'Tĩnh mạch tim giữa','Vena cordis media','Vena media cordis','Middle cardiac vein','coronary',0,'Đi trong rãnh gian thất sau cùng nhánh gian thất sau, đổ vào xoang vành.','Dẫn máu tĩnh mạch từ mặt hoành của tim về xoang vành.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now()),
('inferior_vein_lv','cardiovascular',array['Inferior vein of left ventricle','Inferior vein of left ventricle (//Posterior '''')']::text[],'Tĩnh mạch sau tâm thất trái','Vena ventriculi sinistri posterior','Vena inferior ventriculi sinistri','Posterior (inferior) vein of left ventricle','coronary',0,'Đi trên mặt hoành của tâm thất trái, đổ vào xoang vành hoặc tĩnh mạch tim lớn.','Dẫn máu tĩnh mạch từ mặt dưới tâm thất trái.',null,null,'BẢN NHÁP – chưa có cố vấn duyệt',null,null,now())
on conflict (id) do update set system=excluded.system,mesh_names=excluded.mesh_names,name_vi=excluded.name_vi,name_latin=excluded.name_latin,name_latin_ta2=excluded.name_latin_ta2,name_en=excluded.name_en,grp=excluded.grp,layer=excluded.layer,description=excluded.description,"function"=excluded."function",clinical=excluded.clinical,mnemonic=excluded.mnemonic,source=excluded.source,reviewed_by=excluded.reviewed_by,reviewed_at=excluded.reviewed_at,updated_at=now();
delete from public.structure_sources where structure_id in (select id from public.structures where system='cardiovascular');
insert into public.structure_sources (structure_id,source_id) values
('right_atrium','ta2'),
('right_atrium','gray1918'),
('right_atrium','wiki_heart'),
('right_atrium','openstax_ap_19'),
('right_ventricle','ta2'),
('right_ventricle','gray1918'),
('right_ventricle','wiki_heart'),
('right_ventricle','openstax_ap_19'),
('left_atrium','ta2'),
('left_atrium','gray1918'),
('left_atrium','wiki_heart'),
('left_atrium','openstax_ap_19'),
('left_atrium','haissaguerre1998'),
('left_atrium','carapetis2016rhd'),
('left_ventricle','ta2'),
('left_ventricle','gray1918'),
('left_ventricle','wiki_heart'),
('left_ventricle','openstax_ap_19'),
('left_ventricle','levy1990lvh'),
('papillary_muscles_rv','ta2'),
('papillary_muscles_rv','gray1918'),
('papillary_muscles_rv','wiki_heart'),
('papillary_muscles_rv','openstax_ap_19'),
('papillary_muscle_lv','ta2'),
('papillary_muscle_lv','gray1918'),
('papillary_muscle_lv','wiki_heart'),
('papillary_muscle_lv','openstax_ap_19'),
('papillary_muscle_lv','ho2002mitral'),
('tricuspid_valve','ta2'),
('tricuspid_valve','gray1918'),
('tricuspid_valve','wiki_heart'),
('tricuspid_valve','openstax_ap_19'),
('mitral_valve','ta2'),
('mitral_valve','gray1918'),
('mitral_valve','wiki_heart'),
('mitral_valve','openstax_ap_19'),
('mitral_valve','ho2002mitral'),
('mitral_valve','carapetis2016rhd'),
('aortic_valve','ta2'),
('aortic_valve','gray1918'),
('aortic_valve','wiki_heart'),
('aortic_valve','openstax_ap_19'),
('aortic_valve','piazza2008aortic'),
('pulmonary_valve','ta2'),
('pulmonary_valve','gray1918'),
('pulmonary_valve','wiki_heart'),
('pulmonary_valve','openstax_ap_19'),
('ascending_aorta','ta2'),
('ascending_aorta','gray1918'),
('ascending_aorta','wiki_heart'),
('ascending_aorta','openstax_ap_19'),
('ascending_aorta','piazza2008aortic'),
('aortic_arch','ta2'),
('aortic_arch','gray1918'),
('aortic_arch','wiki_heart'),
('aortic_arch','openstax_ap_19'),
('thoracic_aorta','ta2'),
('thoracic_aorta','gray1918'),
('thoracic_aorta','wiki_heart'),
('thoracic_aorta','openstax_ap_19'),
('brachiocephalic_trunk','ta2'),
('brachiocephalic_trunk','gray1918'),
('brachiocephalic_trunk','wiki_heart'),
('brachiocephalic_trunk','openstax_ap_19'),
('right_common_carotid','ta2'),
('right_common_carotid','gray1918'),
('right_common_carotid','wiki_heart'),
('right_common_carotid','openstax_ap_19'),
('left_common_carotid','ta2'),
('left_common_carotid','gray1918'),
('left_common_carotid','wiki_heart'),
('left_common_carotid','openstax_ap_19'),
('right_subclavian','ta2'),
('right_subclavian','gray1918'),
('right_subclavian','wiki_heart'),
('right_subclavian','openstax_ap_19'),
('left_subclavian','ta2'),
('left_subclavian','gray1918'),
('left_subclavian','wiki_heart'),
('left_subclavian','openstax_ap_19'),
('pulmonary_trunk','ta2'),
('pulmonary_trunk','gray1918'),
('pulmonary_trunk','wiki_heart'),
('pulmonary_trunk','openstax_ap_19'),
('right_pulmonary_artery','ta2'),
('right_pulmonary_artery','gray1918'),
('right_pulmonary_artery','wiki_heart'),
('right_pulmonary_artery','openstax_ap_19'),
('left_pulmonary_artery','ta2'),
('left_pulmonary_artery','gray1918'),
('left_pulmonary_artery','wiki_heart'),
('left_pulmonary_artery','openstax_ap_19'),
('superior_vena_cava','ta2'),
('superior_vena_cava','gray1918'),
('superior_vena_cava','wiki_heart'),
('superior_vena_cava','openstax_ap_19'),
('superior_vena_cava','wilson2007svc'),
('inferior_vena_cava','ta2'),
('inferior_vena_cava','gray1918'),
('inferior_vena_cava','wiki_heart'),
('inferior_vena_cava','openstax_ap_19'),
('right_brachiocephalic_vein','ta2'),
('right_brachiocephalic_vein','gray1918'),
('right_brachiocephalic_vein','wiki_heart'),
('right_brachiocephalic_vein','openstax_ap_19'),
('left_brachiocephalic_vein','ta2'),
('left_brachiocephalic_vein','gray1918'),
('left_brachiocephalic_vein','wiki_heart'),
('left_brachiocephalic_vein','openstax_ap_19'),
('right_pulmonary_veins','ta2'),
('right_pulmonary_veins','gray1918'),
('right_pulmonary_veins','wiki_heart'),
('right_pulmonary_veins','openstax_ap_19'),
('right_pulmonary_veins','haissaguerre1998'),
('left_pulmonary_veins','ta2'),
('left_pulmonary_veins','gray1918'),
('left_pulmonary_veins','wiki_heart'),
('left_pulmonary_veins','openstax_ap_19'),
('left_pulmonary_veins','haissaguerre1998'),
('left_coronary_artery','ta2'),
('left_coronary_artery','gray1918'),
('left_coronary_artery','wiki_heart'),
('left_coronary_artery','openstax_ap_19'),
('left_coronary_artery','angelini2007coronary'),
('anterior_interventricular_artery','ta2'),
('anterior_interventricular_artery','gray1918'),
('anterior_interventricular_artery','wiki_heart'),
('anterior_interventricular_artery','openstax_ap_19'),
('anterior_interventricular_artery','angelini2007coronary'),
('circumflex_artery','ta2'),
('circumflex_artery','gray1918'),
('circumflex_artery','wiki_heart'),
('circumflex_artery','openstax_ap_19'),
('circumflex_artery','angelini2007coronary'),
('right_coronary_artery','ta2'),
('right_coronary_artery','gray1918'),
('right_coronary_artery','wiki_heart'),
('right_coronary_artery','openstax_ap_19'),
('right_coronary_artery','angelini2007coronary'),
('coronary_sinus','ta2'),
('coronary_sinus','gray1918'),
('coronary_sinus','wiki_heart'),
('coronary_sinus','openstax_ap_19'),
('great_cardiac_vein','ta2'),
('great_cardiac_vein','gray1918'),
('great_cardiac_vein','wiki_heart'),
('great_cardiac_vein','openstax_ap_19'),
('middle_cardiac_vein','ta2'),
('middle_cardiac_vein','gray1918'),
('middle_cardiac_vein','wiki_heart'),
('middle_cardiac_vein','openstax_ap_19'),
('inferior_vein_lv','ta2'),
('inferior_vein_lv','gray1918'),
('inferior_vein_lv','wiki_heart'),
('inferior_vein_lv','openstax_ap_19');
delete from public.questions where system='cardiovascular';
insert into public.questions (id,system,type,prompt,target_structure_id,distractor_ids,difficulty,tags) values
('q001','cardiovascular','click','Nhấp vào tâm thất trái','left_ventricle',null,1,array['chambers']::text[]),
('q002','cardiovascular','click','Nhấp vào tâm nhĩ phải','right_atrium',null,1,array['chambers']::text[]),
('q003','cardiovascular','click','Nhấp vào buồng tim nhận máu từ các tĩnh mạch phổi','left_atrium',null,2,array['chambers']::text[]),
('q004','cardiovascular','click','Nhấp vào buồng tim tạo nên phần lớn mặt ức sườn','right_ventricle',null,2,array['chambers']::text[]),
('q005','cardiovascular','click','Nhấp vào van hai lá','mitral_valve',null,1,array['valves']::text[]),
('q006','cardiovascular','click','Nhấp vào van ba lá','tricuspid_valve',null,1,array['valves']::text[]),
('q007','cardiovascular','click','Nhấp vào van động mạch chủ','aortic_valve',null,2,array['valves']::text[]),
('q008','cardiovascular','click','Nhấp vào cung động mạch chủ','aortic_arch',null,1,array['great_arteries']::text[]),
('q009','cardiovascular','click','Nhấp vào thân động mạch phổi','pulmonary_trunk',null,1,array['great_arteries']::text[]),
('q010','cardiovascular','click','Nhấp vào nhánh đầu tiên của cung động mạch chủ','brachiocephalic_trunk',null,2,array['great_arteries']::text[]),
('q011','cardiovascular','click','Nhấp vào động mạch dưới đòn trái','left_subclavian',null,2,array['great_arteries']::text[]),
('q012','cardiovascular','click','Nhấp vào tĩnh mạch chủ trên','superior_vena_cava',null,1,array['great_veins']::text[]),
('q013','cardiovascular','click','Nhấp vào tĩnh mạch chủ dưới','inferior_vena_cava',null,1,array['great_veins']::text[]),
('q014','cardiovascular','click','Nhấp vào tĩnh mạch cánh tay đầu trái','left_brachiocephalic_vein',null,2,array['great_veins']::text[]),
('q015','cardiovascular','click','Nhấp vào động mạch vành phải','right_coronary_artery',null,2,array['coronary']::text[]),
('q016','cardiovascular','click','Nhấp vào nhánh gian thất trước','anterior_interventricular_artery',null,2,array['coronary']::text[]),
('q017','cardiovascular','click','Nhấp vào tĩnh mạch đổ phần lớn máu tĩnh mạch của tim về tâm nhĩ phải','coronary_sinus',null,3,array['coronary']::text[]),
('q018','cardiovascular','click','Nhấp vào nhánh mũ','circumflex_artery',null,3,array['coronary']::text[]),
('q019','cardiovascular','name',null,'aortic_valve',array['pulmonary_valve','mitral_valve','tricuspid_valve']::text[],2,array['valves']::text[]),
('q020','cardiovascular','name',null,'right_atrium',array['left_atrium','right_ventricle','left_ventricle']::text[],1,array['chambers']::text[]),
('q021','cardiovascular','name',null,'left_pulmonary_artery',array['right_pulmonary_artery','pulmonary_trunk','left_pulmonary_veins']::text[],2,array['great_arteries']::text[]),
('q022','cardiovascular','name',null,'left_common_carotid',array['brachiocephalic_trunk','left_subclavian','right_common_carotid']::text[],2,array['great_arteries']::text[]),
('q023','cardiovascular','name',null,'great_cardiac_vein',array['middle_cardiac_vein','anterior_interventricular_artery','coronary_sinus']::text[],3,array['coronary']::text[]),
('q024','cardiovascular','name',null,'right_pulmonary_veins',array['left_pulmonary_veins','superior_vena_cava','right_pulmonary_artery']::text[],2,array['great_veins']::text[]),
('q025','cardiovascular','click','Nhấp vào buồng tim có thành dày nhất','left_ventricle',null,2,array['chambers']::text[]),
('q026','cardiovascular','click','Nhấp vào buồng tim chứa nút xoang nhĩ','right_atrium',null,2,array['chambers']::text[]),
('q027','cardiovascular','click','Nhấp vào buồng tim bơm máu lên phổi','right_ventricle',null,1,array['chambers']::text[]),
('q028','cardiovascular','click','Nhấp vào buồng tim nằm sau nhất, tạo nên nền tim','left_atrium',null,2,array['chambers']::text[]),
('q029','cardiovascular','click','Nhấp vào cơ nhú của tâm thất phải','papillary_muscles_rv',null,3,array['chambers']::text[]),
('q030','cardiovascular','click','Nhấp vào cơ nhú của tâm thất trái','papillary_muscle_lv',null,3,array['chambers']::text[]),
('q031','cardiovascular','name',null,'left_ventricle',array['right_ventricle','left_atrium','right_atrium']::text[],1,array['chambers']::text[]),
('q032','cardiovascular','name',null,'right_ventricle',array['left_ventricle','right_atrium','pulmonary_trunk']::text[],1,array['chambers']::text[]),
('q033','cardiovascular','name',null,'left_atrium',array['right_atrium','left_ventricle','left_pulmonary_veins']::text[],2,array['chambers']::text[]),
('q034','cardiovascular','name',null,'papillary_muscles_rv',array['papillary_muscle_lv','tricuspid_valve','right_ventricle']::text[],3,array['chambers']::text[]),
('q035','cardiovascular','click','Nhấp vào van ngăn máu trào ngược từ thất trái lên nhĩ trái','mitral_valve',null,2,array['valves']::text[]),
('q036','cardiovascular','click','Nhấp vào van có ba lá nằm giữa nhĩ phải và thất phải','tricuspid_valve',null,2,array['valves']::text[]),
('q037','cardiovascular','click','Nhấp vào van nằm ở lỗ thân động mạch phổi','pulmonary_valve',null,2,array['valves']::text[]),
('q038','cardiovascular','click','Nhấp vào van mà ngay phía trên nó xuất phát hai động mạch vành','aortic_valve',null,3,array['valves']::text[]),
('q039','cardiovascular','name',null,'mitral_valve',array['tricuspid_valve','aortic_valve','pulmonary_valve']::text[],1,array['valves']::text[]),
('q040','cardiovascular','name',null,'tricuspid_valve',array['mitral_valve','pulmonary_valve','aortic_valve']::text[],1,array['valves']::text[]),
('q041','cardiovascular','name',null,'pulmonary_valve',array['aortic_valve','tricuspid_valve','pulmonary_trunk']::text[],2,array['valves']::text[]),
('q042','cardiovascular','click','Nhấp vào động mạch chủ lên','ascending_aorta',null,1,array['great_arteries']::text[]),
('q043','cardiovascular','click','Nhấp vào động mạch chủ ngực','thoracic_aorta',null,2,array['great_arteries']::text[]),
('q044','cardiovascular','click','Nhấp vào động mạch cảnh chung trái','left_common_carotid',null,2,array['great_arteries']::text[]),
('q045','cardiovascular','click','Nhấp vào động mạch cảnh chung phải','right_common_carotid',null,2,array['great_arteries']::text[]),
('q046','cardiovascular','click','Nhấp vào động mạch dưới đòn phải','right_subclavian',null,2,array['great_arteries']::text[]),
('q047','cardiovascular','click','Nhấp vào động mạch phổi phải','right_pulmonary_artery',null,2,array['great_arteries']::text[]),
('q048','cardiovascular','click','Nhấp vào động mạch phổi trái','left_pulmonary_artery',null,2,array['great_arteries']::text[]),
('q049','cardiovascular','click','Nhấp vào nhánh thứ ba của cung động mạch chủ','left_subclavian',null,3,array['great_arteries']::text[]),
('q050','cardiovascular','name',null,'aortic_arch',array['ascending_aorta','thoracic_aorta','pulmonary_trunk']::text[],1,array['great_arteries']::text[]),
('q051','cardiovascular','name',null,'brachiocephalic_trunk',array['left_common_carotid','right_common_carotid','right_subclavian']::text[],2,array['great_arteries']::text[]),
('q052','cardiovascular','name',null,'pulmonary_trunk',array['ascending_aorta','superior_vena_cava','left_pulmonary_artery']::text[],1,array['great_arteries']::text[]),
('q053','cardiovascular','name',null,'right_subclavian',array['left_subclavian','right_common_carotid','brachiocephalic_trunk']::text[],3,array['great_arteries']::text[]),
('q054','cardiovascular','click','Nhấp vào các tĩnh mạch phổi phải','right_pulmonary_veins',null,2,array['great_veins']::text[]),
('q055','cardiovascular','click','Nhấp vào các tĩnh mạch phổi trái','left_pulmonary_veins',null,2,array['great_veins']::text[]),
('q056','cardiovascular','click','Nhấp vào tĩnh mạch cánh tay đầu phải','right_brachiocephalic_vein',null,2,array['great_veins']::text[]),
('q057','cardiovascular','click','Nhấp vào tĩnh mạch đi qua cơ hoành ở mức đốt sống ngực VIII','inferior_vena_cava',null,3,array['great_veins']::text[]),
('q058','cardiovascular','name',null,'superior_vena_cava',array['inferior_vena_cava','right_brachiocephalic_vein','ascending_aorta']::text[],1,array['great_veins']::text[]),
('q059','cardiovascular','name',null,'left_brachiocephalic_vein',array['right_brachiocephalic_vein','superior_vena_cava','left_subclavian']::text[],2,array['great_veins']::text[]),
('q060','cardiovascular','name',null,'left_pulmonary_veins',array['right_pulmonary_veins','left_pulmonary_artery','pulmonary_trunk']::text[],2,array['great_veins']::text[]),
('q061','cardiovascular','click','Nhấp vào động mạch vành trái','left_coronary_artery',null,2,array['coronary']::text[]),
('q062','cardiovascular','click','Nhấp vào tĩnh mạch tim lớn','great_cardiac_vein',null,3,array['coronary']::text[]),
('q063','cardiovascular','click','Nhấp vào tĩnh mạch tim giữa','middle_cardiac_vein',null,3,array['coronary']::text[]),
('q064','cardiovascular','click','Nhấp vào xoang vành','coronary_sinus',null,2,array['coronary']::text[]),
('q065','cardiovascular','click','Nhấp vào động mạch thường cấp máu cho nút nhĩ thất','right_coronary_artery',null,3,array['coronary']::text[]),
('q066','cardiovascular','name',null,'anterior_interventricular_artery',array['circumflex_artery','right_coronary_artery','great_cardiac_vein']::text[],2,array['coronary']::text[]),
('q067','cardiovascular','name',null,'circumflex_artery',array['anterior_interventricular_artery','left_coronary_artery','inferior_vein_lv']::text[],3,array['coronary']::text[]),
('q068','cardiovascular','name',null,'coronary_sinus',array['middle_cardiac_vein','great_cardiac_vein','inferior_vena_cava']::text[],2,array['coronary']::text[]),
('q069','cardiovascular','name',null,'left_coronary_artery',array['right_coronary_artery','anterior_interventricular_artery','circumflex_artery']::text[],2,array['coronary']::text[]),
('q070','cardiovascular','name',null,'middle_cardiac_vein',array['great_cardiac_vein','inferior_vein_lv','coronary_sinus']::text[],3,array['coronary']::text[]);
insert into public.content_versions (system,version,git_sha,n_structures,n_questions,n_sources) values ('cardiovascular','0.3.0-draft','fab67f4',35,70,12);
commit;
